import uuid
import os
from pathlib import Path

# "realistic photo",
# "illustration",
# "cartoon",
# "comic",
# "dark",
# "water color",
# "pixel art",
# "surreal",
# "oil painting",
# "nature",
# "ink print",
# "pencil",
# "retrowave",
# "vintage japanese",
# "lifestyle",
# "collage",
# "glitchart",
# "retroglow",
# "lowkey cinematic",
# "analog memories",
# "trippy illustration",
# "fantasy cartoon",
# "pastel paint",
# "arcadebits",
# "squishy 3d",
# "product photography",
# "historical",
# "felted",
# "podium",
# "redveil",
# "darklight dreamscaped",
# "dreamlandscapes",
# "linework",
# "sonny anime",
# "soft pasty",
# "soft retro",
# "plushy world",
# "film effect",
# "anime",
# "warnand cold",
# "sparking",
# "blurry long exposure",
# "flutted glass",
# "glimmerish",
# "forties influence",
# "dadapop",
# "eighties movie",
# "renaissance fashion",
# "fineart",
# "neo classicart",
# "highend light",
# "anime",
# "3d colorful",
# "anime"


THUMBNAIL_STYLE_LIST = [
    "realistic photo",
    # "3d realistic",
    # "3d colorful"
]

GEMINI_KEY_TOOL_RENDER = [
    # "AIzaSyCRZYMR_cqC5XdJ6wi4cO7Tch-knO_WtW4",
    # "AIzaSyBDi2wGNLiAD6iqncKZrGRZThKg_z-3I6c",
    # "AIzaSyCk9FrUaN_C9245Z_B3DvtzDggWu2ksCBg",
    # "AIzaSyBIX2kBeAS21wJUU05sJDB_0su1PiLJz_w",
    # "AIzaSyDetmj90xmAkybYuuMM4DXUc4Tc0hIRj-M",
    # "AIzaSyDP91xrK7B6zjnf0jKeRudguSUO-GHyhmQ",
    # "AIzaSyB8xGKrZBVfosfMIYnddX68hypfwZSY6dA",
    "AIzaSyDPNa--yBNIRGOkNKuNYU4tnVeDQsOVMSs"
]

GEMINI_KEY_TEAM_AUTOMATION = [
    # "AIzaSyDlO7yQAKhOafl6N5FT8O6dtMI3DKEROpg",
    # "AIzaSyDsvs2FqI213De7KH0sPYhCjgVcxDsJhAs",
    # "AIzaSyDQWtvW0-J88JhQ2-pkhRjMc1EGn0S0q-A",
    # "AIzaSyDI87mVYJ1yqUdBWguUPOpMS1U441YRtdA",
    # "AIzaSyCbFla1wYfzexbnwyd25jayJSM8IOlXWuc",
    # "AIzaSyAR7gTd2tu_y1XsGeTnVf1hZiv6BHs_CZA",
    # "AIzaSyAGuUI4P2PcUj5n8AOnbtVQHf4H8hbv4ZU",
    # "AIzaSyBq1C036iuzXp3f3EHrUU84b1fCP16xdpY",
    # "AIzaSyD0cry8PM9mSltSrvQxXwxWyvO4iYBi_ZA",
    # "AIzaSyDxaXcenPFLOIu39R7DIsbEo2tvMUAd_Bc",
    # "AIzaSyA3yKhWEcKxJ5YDLjONUjUkvDLB3mBQmfc",
    # "AIzaSyBxrbjQUL2cu5QLdRBkdp6pW9cv31FrrJA",
    # "AIzaSyDxaXcenPFLOIu39R7DIsbEo2tvMUAd_Bc",
    # "AIzaSyBxrbjQUL2cu5QLdRBkdp6pW9cv31FrrJA",
    # "AIzaSyDRPU-XEQzzX13AMKo_At0St0uqEQWAlqA",
    # "AIzaSyA85MP5jctMT9rKVR6gT16tEmsuO4JqpLg",
    # "AIzaSyCDzXlBfi5lRt2iLY5PT3NSodB-uVbcDuY",
    # "AIzaSyDJ2tjhP0xxDv7EJkJZwe0_g50qULOTDno",
    # "AIzaSyAV0LDFJk_ANuVW6ZHteJAUzF5U0Mq9BBE",
    "AIzaSyDPNa--yBNIRGOkNKuNYU4tnVeDQsOVMSs"
]

SUBFOLDER_TOOL_RENDER = 'tool_render'
SUBFOLDER_TEAM_AUTOMATION = 'team_automation'

MAX_IMAGES_THRESHOLD = 36000
COUNT_IMAGES_TO_DELETE = 5
FLUX_LORA_STEP = {
    'team_automation': 30,
    'tool_render': 30,
}

DEFAULT_FILENAME_PREFIX = 'ytbthumb'

CLIENT_ID = str(uuid.uuid4())

FILE_DIRECTORY = Path(os.getenv('OUTPUT_IMAGE_FOLDER', "/thumbnail_img"))

THUMBNAIL_PER_TIMES = 2

THUMBNAIL_SIZES = {
    'fullhd': {
        'original': {
            'width': 1280,
            'height': 720
        },
        'scaled': {
            'width': 1920,
            'height': 1080
        },
    },
    'rectangle': {
        'original': {
            'width': 1200,
            'height': 1200
        },
        'scaled': {
            'width': 1500,
            'height': 1500
        },
    },
}

INIT_CHARACTER_REQUEST = [
    # {
    #     "short_description": [
    #         "3D style, A detailed depiction of Miles Morales from 'Spider-Man: Beyond the Spider-Verse' sitting on a futuristic chair, reading a book in a serene and immersive space. The environment features intricate neon-lit cityscape architecture visible through a large window, giving a sense of depth. Miles is wearing his signature black and red Spider-Man suit, with the mask partially removed, revealing his thoughtful expression as he focuses on the book. His pose is relaxed, with one leg crossed over the other, and the book resting in his hands. The lighting is a mix of warm ambient light from the room and the cool glow of neon lights outside, creating a balanced and captivating atmosphere. The perspective emphasizes the depth of the room, with bookshelves and technological elements subtly included in the background",
    #         "3D style, A creative and atmospheric scene featuring Miles Morales from 'Spider-Man: Beyond the Spider-Verse' sitting cross-legged on a levitating platform surrounded by books floating in mid-air. He is immersed in reading an ancient-looking, glowing tome, with his Spider-Man suit augmented by subtle, futuristic tech accents. The backdrop features a stunning, layered view of a sprawling, vibrant futuristic cityscape with countless flying vehicles and colorful neon lights extending into the horizon. The lighting is otherworldly, combining soft glows from the floating books, the warm glow of Miles' tome, and the cool, radiant lights from the city beyond. The overall feel is imaginative and deeply immersive, with dynamic depth and motion in the scene",
    #     ],
    #     "title": "",
    #     "file_name": "spiderman_music",
    #     "day_of_week": [0,1,2,3,4,5,6],
    # },
    # {
    #     "short_description": [
    #         "3D style, Sasuke Uchiha from 'Naruto' sitting on a traditional Japanese wooden veranda, reading a book with a calm, introspective expression. He is dressed in his classic dark blue outfit with the Uchiha clan symbol visible on his back. His posture is relaxed, with one leg bent and the other extended forward, the book resting lightly in his hands. The background features a serene, lush garden with a koi pond, blooming cherry blossoms, and soft rays of sunlight filtering through the trees, creating a tranquil and deeply immersive atmosphere. The perspective captures the depth of the garden, with the horizon gently fading into misty mountains",
    #         "3D style, Sasuke Uchiha from 'Naruto' seated in a grand, ancient library filled with towering shelves of scrolls and books, exuding an aura of mystery and depth. He is wearing his Akatsuki cloak, slightly open to reveal his traditional attire underneath. His pose is composed, sitting cross-legged on a raised platform, intently reading a worn-out scroll illuminated by the warm glow of a single hanging lantern. The surrounding library features intricate wooden carvings and beams, with shadows stretching into the distance to emphasize the scale and depth of the space. The atmosphere is quiet and contemplative, enhanced by the subtle contrast of warm light and dark shadows",
    #         ],
    #     "title": "",
    #     "file_name": "sasuke_music",
    #     "day_of_week": [0,1,2,3,4,5,6],
    # },
    # {
    #     "short_description": [
    #         "3D style, Levi Ackerman from 'Attack on Titan' sitting on a simple wooden chair by a large window, reading a book with a calm, focused expression. He is wearing his signature Survey Corps uniform, with the green cloak draped casually over the back of the chair. His posture is upright yet relaxed, one leg crossed over the other, holding the book in his gloved hands. The setting features a sunlit interior of an old, rustic room with wooden beams and stone walls, while the window reveals a vast, peaceful landscape of rolling hills and distant mountains. The soft natural light streaming through the window highlights the textures of the room and the details of Levi’s attire, creating an immersive and serene atmosphere",
    #         "3D style, Levi Ackerman from 'Attack on Titan' seated at a wooden table in a dimly lit study, engrossed in reading a leather-bound book. He is dressed in his formal Survey Corps attire, with his cravat slightly loosened, adding a touch of casual elegance to his composed demeanor. The study is filled with tall shelves lined with books and scattered with maps and papers, exuding a scholarly atmosphere. A single candle on the table casts a warm, flickering glow, contrasting with the cool shadows that stretch into the background, enhancing the room's depth. Levi’s focused gaze and the subtle interplay of light and shadow create an atmosphere of quiet intensity and intellectual curiosity",
    #     ],
    #     "title": "",
    #     "file_name": "levi_ackerman_music",
    #     "day_of_week": [0,1,2,3,4,5,6],
    # },
    # {
    #     "short_description": [
    #         "3D style, Nezuko Kamado from 'Demon Slayer' sitting gracefully on a traditional tatami mat in a cozy Japanese-style room, reading a beautifully illustrated book with a curious and peaceful expression. She is wearing her signature pink kimono with a geometric pattern, her hair neatly tied with a ribbon, and the bamboo muzzle resting beside her on the floor. The room is softly lit by the warm glow of a paper lantern, and the sliding shoji doors are partially open, revealing a tranquil garden with bamboo groves and the soft glow of fireflies in the evening light. The composition emphasizes the depth of the room and the serenity of the setting, blending the indoor warmth with the outdoor calm",
    #         "3D style, Nezuko Kamado from 'Demon Slayer' seated on a large tree stump in a forest clearing, intently reading a small, worn book resting on her lap. She is dressed in her traditional pink and black outfit, her haori draping slightly over the edge of the stump. Surrounding her are towering trees with sunlight filtering through the leaves, creating dappled light patterns on the ground and adding depth to the forest scene. Nearby, small forest animals, like rabbits and birds, curiously gather around her as she reads, adding a whimsical and heartwarming touch to the peaceful atmosphere",
    #         ],
    #     "title": "",
    #     "file_name": "nezuko_music",
    #     "day_of_week": [0,1,2,3,4,5,6],
    # },
    # {
    #     "short_description": [
    #         "3D style, Vegeta from 'Dragon Ball' sitting cross-legged on a rocky cliff, meditating with a focused and intense expression. He is dressed in his classic Saiyan armor, slightly weathered from training, and his arms rest calmly on his knees. The cliff overlooks a vast, otherworldly landscape with glowing blue rivers, jagged rock formations, and distant mountains under a dramatic sky filled with swirling clouds and a glowing sunset. His aura faintly shimmers with energy, blending into the ambient light, creating an atmosphere of power and tranquility. The composition highlights the immense depth of the terrain, with Vegeta's form silhouetted against the expansive horizon",
    #         "3D style, Vegeta from 'Dragon Ball' meditating in a serene Saiyan training chamber, designed with futuristic, minimalist architecture. He sits in the center of a glowing circular platform, cross-legged, eyes closed, and his body surrounded by a faint, flickering golden aura. The chamber features high ceilings and an open skylight, revealing a star-filled sky with distant planets visible. Energy patterns ripple subtly across the platform, and the soft hum of power in the air adds a sense of intensity and focus. The depth of the chamber is emphasized by the receding walls, illuminated with soft, glowing lines, creating a meditative and futuristic atmosphere",
    #         ],
    #     "title": "",
    #     "file_name": "vegeta_music",
    #     "day_of_week": [0,1,2,3,4,5,6],
    # },
    # {
    #     "short_description": [
    #         "3D style, Roronoa Zoro from 'One Piece' sitting cross-legged on a grassy hilltop at sunrise, meditating with a calm yet focused expression. His iconic green haramaki and swords are resting nearby, carefully arranged beside him. The hill overlooks a sprawling ocean with waves glistening under the soft golden light of dawn, and distant islands barely visible on the horizon. Gentle wind rustles the grass and carries the sound of the waves, adding a serene and immersive atmosphere. The depth of the scene is emphasized by the contrast between the close details of Zoro’s posture and the vast, open landscape stretching into the distance",
    #     ],
    #     "title": "",
    #     "file_name": "zoro_music",
    #     "day_of_week": [0,1,2,3,4,5,6],
    # },
]

INIT_50_ANIMAL_REQUEST = [
    {
        "short_description": [
            "A Capybara under cherry blossoms, headphones on, vintage cassette, pastel sunlight glow, serene and lofi atmosphere, anime watercolor painting style",
            "A Capybara at desk by window, sketching, coffee, lofi music, bright garden view, warm and cheerful setting, anime watercolor painting style",
            "A Capybaras lounging by river, headphones, stylish hats, blooming flowers, sunny day, playful and lofi mood, anime watercolor painting style",
            "A Capybara on bench, vintage player, sunset cityscape, vibrant lights, greenery, calm and nostalgic vibe, anime watercolor painting style",
            "A Capybara in hammock, sunglasses on, vinyl player nearby, bright beach scene, soft waves, and relaxed lofi energy, anime watercolor painting style",
            "A Capybara at park table, scarf on, sketching notebook, autumn leaves, golden sunlight, cozy and artistic ambiance, anime watercolor painting style",
            "A Capybara on balcony, tea in hand, sunrise cityscape, vibrant hues, peaceful lofi vibes, bright and serene, anime watercolor painting style",
            "A Capybara in cozy room, surrounded by books, fairy lights, pastel tones, lofi beats playing, warm and inviting, anime watercolor painting style",
            "A Capybara on a boat, record player spinning, calm lake reflections, blooming flowers, bright sky, peaceful lofi moment, anime watercolor painting style",
            "A Capybara on tree stump, headphones on, small radio, wildflowers surrounding, sunlight beams, cheerful forest lofi scene, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "capybara_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Scottish Fold cat under cherry blossoms, headphones on, vintage cassette, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Scottish Fold cat at a desk by a window, sketching, coffee nearby, lofi music playing, warm light, cheerful ambiance, anime watercolor painting style",
            "A Scottish Fold cat lounging by a river, headphones on, blooming flowers, sunny day, playful and relaxed lofi mood, anime watercolor painting style",
            "A Scottish Fold cat on a park bench, vintage player, sunset view, vibrant greenery, calm and nostalgic lofi atmosphere, anime watercolor painting style",
            "A Scottish Fold cat in a hammock, sunglasses on, vinyl spinning, bright beach scene, soft waves, relaxed lofi vibe, anime watercolor painting style",
            "A Scottish Fold cat at a park table, scarf on, sketching notebook, golden sunlight, autumn leaves, cozy lofi setting, anime watercolor painting style",
            "A Scottish Fold cat on a balcony, tea in paw, sunrise cityscape, vibrant hues, serene and peaceful lofi moment, anime watercolor painting style",
            "A Scottish Fold cat in a cozy room, books stacked, fairy lights glowing, pastel tones, warm and inviting lofi mood, anime watercolor painting style",
            "A Scottish Fold cat on a boat, record player spinning, calm lake reflections, blooming flowers, bright, serene lofi setting, anime watercolor painting style",
            "A Scottish Fold cat on a tree stump, headphones on, small radio playing, wildflowers, sunlight beams, cheerful forest lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "scottish_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Shiba Inu under cherry blossoms, headphones on, vintage cassette, pastel sunlight glow, serene and cheerful lofi vibe, anime watercolor painting style",
            "A Shiba Inu at a desk by a window, sketching, coffee nearby, lofi music playing, warm light, and bright ambiance, anime watercolor painting style",
            "A Shiba Inu lounging by a river, headphones on, blooming flowers, sunny day, playful and relaxed lofi atmosphere, anime watercolor painting style",
            "A Shiba Inu on a park bench, vintage player, sunset view, vibrant greenery, calm and nostalgic lofi scene, anime watercolor painting style",
            "A Shiba Inu in a hammock, sunglasses on, vinyl spinning, bright beach setting, soft waves, and relaxed lofi vibe, anime watercolor painting style",
            "A Shiba Inu at a park table, scarf on, sketching notebook, golden sunlight, autumn leaves, cozy and artistic lofi mood, anime watercolor painting style",
            "A Shiba Inu on a balcony, tea in paw, sunrise cityscape, vibrant hues, serene and peaceful lofi moment, anime watercolor painting style",
            "A Shiba Inu in a cozy room, books stacked, fairy lights glowing, pastel tones, warm, and inviting lofi ambiance, anime watercolor painting style",
            "A Shiba Inu on a boat, record player spinning, calm lake reflections, blooming flowers, bright and serene lofi setting, anime watercolor painting style",
            "A Shiba Inu on a tree stump, headphones on, small radio playing, wildflowers, sunlight beams, cheerful forest lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "shiba_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Holland Lop rabbit under cherry blossoms, wearing headphones, listening to lofi music, pastel sunlight glow, serene, anime watercolor painting style",
            "A Holland Lop rabbit sitting at a desk by a window, sketching, coffee nearby, warm light, cheerful lofi atmosphere, anime watercolor painting style",
            "A Holland Lop rabbit lounging by a river, headphones on, blooming flowers, sunny day, playful and relaxed lofi scene, anime watercolor painting style",
            "A Holland Lop rabbit on a park bench, vintage player nearby, sunset view, vibrant greenery, nostalgic lofi vibe, anime watercolor painting style",
            "A Holland Lop rabbit in a hammock, sunglasses on, vinyl spinning, bright beach scene, soft waves, relaxed lofi mood, anime watercolor painting style",
            "A Holland Lop rabbit at a park table, scarf on, sketching in a notebook, golden sunlight, cozy autumn lofi vibe, anime watercolor painting style",
            "A Holland Lop rabbit on a balcony, tea in paw, sunrise cityscape, vibrant hues, serene and peaceful lofi setting, anime watercolor painting style",
            "A Holland Lop rabbit in a cozy room, surrounded by books, fairy lights glowing, pastel tones, warm lofi mood, anime watercolor painting style",
            "A Holland Lop rabbit on a boat, record player spinning, calm lake reflections, blooming flowers, serene lofi vibe, anime watercolor painting style",
            "A Holland Lop rabbit on a tree stump, headphones on, listening to lofi beats, wildflowers, sunlight beams, cheerful forest lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "holland_lop_rabbit_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Tawny Owl perched under cherry blossoms, wearing headphones, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Tawny Owl on a windowsill, surrounded by books and a cup of tea, warm light, listening to lofi beats, anime watercolor painting style",
            "A Tawny Owl sitting on a park bench, vintage cassette player nearby, sunset view, vibrant greenery, nostalgic lofi atmosphere, anime watercolor painting style",
            "A Tawny Owl perched on a tree branch by a sparkling river, headphones on, blooming flowers, sunny lofi mood, anime watercolor painting style",
            "A Tawny Owl resting on a wooden balcony, tea cup beside, overlooking a bright sunrise, peaceful lofi ambiance, anime watercolor painting style",
            "A Tawny Owl in a cozy library corner, surrounded by glowing fairy lights and open books, warm pastel tones, lofi beats playing, anime watercolor style",
            "A Tawny Owl perched on a boat’s edge, record player spinning, calm lake reflections, colorful flowers, serene lofi vibe, anime watercolor painting style",
            "A Tawny Owl in a hammock tied between forest trees, listening to lofi music on headphones, bright and peaceful setting, anime watercolor painting style",
            "A Tawny Owl sitting on a tree stump in a sunny meadow, headphones on, radio playing lofi beats, wildflowers around, anime watercolor painting style",
            "A Tawny Owl gazing at a vibrant cityscape from a rooftop, headphones on, tea cup beside, soft lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "tawny_owl_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "An Emperor Penguin under glowing auroras, headphones on, listening to lofi music, icy pastel hues, serene vibe, anime watercolor painting style",
            "An Emperor Penguin sitting on a snowy dock, vintage player nearby, warm sunlight reflecting on ice, peaceful lofi mood, anime watercolor painting style",
            "An Emperor Penguin resting on a beach with palm trees, sunglasses on, vinyl spinning, bright tropical lofi vibe, anime watercolor painting style",
            "An Emperor Penguin on a glacier edge, tea cup in flipper, pastel skies above, calm lofi ambiance, anime watercolor painting style",
            "An Emperor Penguin in a cozy igloo, surrounded by fairy lights and books, listening to lofi music, warm pastel tones, anime watercolor painting style",
            "An Emperor Penguin standing near a frozen river, headphones on, soft sunlight shining, serene lofi atmosphere, anime watercolor painting style",
            "An Emperor Penguin relaxing on a floating ice sheet, vintage cassette player beside, colorful sunset sky, peaceful lofi mood, anime watercolor painting style",
            "An Emperor Penguin gazing at a bright cityscape from a snowy rooftop, tea cup beside, calm lofi beats, anime watercolor painting style",
            "An Emperor Penguin sitting near a glowing bonfire in the Arctic, headphones on, colorful night sky, serene lofi vibe, anime watercolor painting style",
            "An Emperor Penguin perched on an icy hill under soft sunlight, headphones on, radio playing lofi beats, bright pastel tones, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "emperor_penguin_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Red Panda under cherry blossoms, headphones on, vintage cassette, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Red Panda sitting on a tree branch, sketching in a notebook, warm light filtering through leaves, cheerful lofi mood, anime watercolor painting style",
            "A Red Panda lounging near a sparkling stream, headphones on, blooming flowers, sunny day, peaceful lofi scene, anime watercolor painting style",
            "A Red Panda sitting on a park bench, vintage player beside, golden sunset, vibrant greenery, nostalgic lofi vibe, anime watercolor painting style",
            "A Red Panda in a hammock between bamboo trees, listening to vinyl, bright sunlight, relaxed lofi atmosphere, anime watercolor painting style",
            "A Red Panda sitting at a cozy desk by a window, surrounded by books and tea, warm pastel tones, lofi beats playing, anime watercolor painting style",
            "A Red Panda on a mountain edge, tea cup in paw, colorful sunset sky, serene lofi ambiance, anime watercolor painting style",
            "A Red Panda in a cozy forest cabin, fairy lights glowing, vintage cassette playing, inviting pastel tones, lofi vibe, anime watercolor painting style",
            "A Red Panda perched on a boat floating on a calm lake, headphones on, blooming flowers, serene lofi mood, anime watercolor painting style",
            "A Red Panda on a rooftop under a bright cityscape, vintage player, tea cup beside, soft lofi beats, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "red_panda_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Fennec Fox under desert stars, headphones on, listening to lofi music, pastel glow, serene vibe, anime watercolor painting style",
            "A Fennec Fox sitting on a sand dune, vintage cassette nearby, soft sunrise hues, peaceful lofi mood, anime watercolor painting style",
            "A Fennec Fox lounging in an oasis, headphones on, palm trees reflecting on water, bright tropical lofi vibe, anime watercolor painting style",
            "A Fennec Fox on a rooftop terrace, tea cup beside, cityscape at sunrise, calm lofi ambiance, anime watercolor painting style",
            "A Fennec Fox in a cozy tent, surrounded by fairy lights and books, listening to lofi music, warm pastel tones, anime watercolor painting style",
            "A Fennec Fox resting by a campfire in the desert, vintage player playing, colorful night sky, serene lofi atmosphere, anime watercolor painting style",
            "A Fennec Fox perched on a stone ledge, headphones on, glowing canyon backdrop, bright and peaceful lofi scene, anime watercolor painting style",
            "A Fennec Fox sitting at a rustic desk near a window, sketching, warm light streaming, lofi beats playing, anime watercolor painting style",
            "A Fennec Fox relaxing near a sparkling spring, headphones on, blooming wildflowers, sunny desert lofi vibe, anime watercolor painting style",
            "A Fennec Fox on a hammock between two trees, vintage player spinning, vibrant daylight, relaxed lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "fennec_fox_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Flamingo standing in a pastel lagoon, headphones on, listening to lofi music, serene sunlight glow, anime watercolor painting style",
            "A Flamingo by a tranquil pond, vintage player nearby, blooming flowers, bright and cheerful lofi mood, anime watercolor painting style",
            "A Flamingo perched on a dock at sunset, tea cup beside, glowing pastel sky, calm lofi ambiance, anime watercolor painting style",
            "A Flamingo wading in shallow waters surrounded by wildflowers, headphones on, soft sunlight, peaceful lofi vibe, anime watercolor painting style",
            "A Flamingo resting under a palm tree, vinyl spinning, bright tropical beach scene, relaxed lofi atmosphere, anime watercolor painting style",
            "A Flamingo on a rooftop garden, vintage player playing, sunrise cityscape in view, serene lofi setting, anime watercolor painting style",
            "A Flamingo near a sparkling waterfall, headphones on, surrounded by lush greenery, cheerful lofi moment, anime watercolor painting style",
            "A Flamingo in a cozy lakeside cabin, fairy lights glowing, pastel tones, lofi beats playing, warm and inviting, anime watercolor painting style",
            "A Flamingo floating in a calm lake, colorful flowers reflecting on water, vintage cassette nearby, tranquil lofi mood, anime watercolor painting style",
            "A Flamingo perched on a wooden pier, tea cup nearby, pastel sunrise skies, peaceful and vibrant lofi scene, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "flamingo_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Corgi sitting under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight, serene lofi vibe, anime watercolor painting style",
            "A Corgi lounging by a sparkling stream, sketching in a notebook, blooming flowers, bright cheerful lofi mood, anime watercolor painting style",
            "A Corgi on a park bench at sunset, vintage player beside, vibrant greenery, peaceful lofi atmosphere, anime watercolor painting style",
            "A Corgi resting on a picnic blanket, surrounded by flowers and tea, sunny day, relaxed lofi vibe, anime watercolor painting style",
            "A Corgi sitting by a window, books stacked around, fairy lights glowing, warm pastel tones, listening to lofi beats, anime watercolor painting style",
            "A Corgi lying on a boat floating in a calm lake, headphones on, blooming flowers nearby, tranquil lofi scene, anime watercolor painting style",
            "A Corgi in a hammock tied between trees, vintage vinyl spinning, golden sunlight filtering, peaceful lofi mood, anime watercolor painting style",
            "A Corgi sitting on a rooftop terrace, tea cup nearby, cityscape at sunrise, serene lofi ambiance, anime watercolor painting style",
            "A Corgi exploring a vibrant forest path, headphones on, wildflowers blooming, bright and cheerful lofi vibe, anime watercolor painting style",
            "A Corgi relaxing by a cozy fireplace, surrounded by books and a record player, warm and inviting lofi setting, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "corgi_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Munchkin Cat under cherry blossoms, headphones on, vintage cassette, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Munchkin Cat sitting by a window, sketching in a notebook, warm light streaming, cheerful lofi mood, anime watercolor painting style",
            "A Munchkin Cat lounging on a park bench, vintage player beside, sunset view, vibrant greenery, peaceful lofi atmosphere, anime watercolor painting style",
            "A Munchkin Cat resting in a cozy room, surrounded by books and fairy lights, pastel tones, lofi beats playing, anime watercolor painting style",
            "A Munchkin Cat in a hammock tied between trees, vinyl spinning nearby, golden sunlight filtering, relaxed lofi mood, anime watercolor painting style",
            "A Munchkin Cat sitting by a calm stream, headphones on, blooming flowers around, sunny and tranquil lofi scene, anime watercolor painting style",
            "A Munchkin Cat on a rooftop garden, tea cup nearby, cityscape at sunrise, serene lofi vibe, anime watercolor painting style",
            "A Munchkin Cat lying on a boat floating on a calm lake, vintage cassette playing, blooming flowers, peaceful lofi moment, anime watercolor painting style",
            "A Munchkin Cat resting under a tree in a vibrant meadow, headphones on, wildflowers blooming, cheerful lofi atmosphere, anime watercolor painting style",
            "A Munchkin Cat sitting near a glowing fireplace, surrounded by books and a record player, warm lofi setting, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "munchkin_cat_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "An Alpaca under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight, serene lofi vibe, anime watercolor painting style",
            "An Alpaca sitting on a grassy hill, tea cup nearby, glowing sunset, vibrant flowers, peaceful lofi mood, anime watercolor painting style",
            "An Alpaca lounging by a calm stream, surrounded by blooming wildflowers, headphones on, bright cheerful lofi scene, anime watercolor painting style",
            "An Alpaca in a cozy wooden cabin, surrounded by books and fairy lights, lofi music playing, warm pastel tones, anime watercolor painting style",
            "An Alpaca resting on a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi ambiance, anime watercolor painting style",
            "An Alpaca on a mountain path, sketchbook in front, headphones on, colorful sunrise sky, tranquil lofi vibe, anime watercolor painting style",
            "An Alpaca sitting near a sparkling lake, vintage player nearby, blooming flowers, serene lofi atmosphere, anime watercolor painting style",
            "An Alpaca in a rooftop garden, surrounded by plants and a tea set, sunrise cityscape view, peaceful lofi moment, anime watercolor painting style",
            "An Alpaca standing by a campfire in a meadow, headphones on, glowing night sky, relaxed lofi scene, anime watercolor painting style",
            "An Alpaca perched on a wooden fence, pastel fields stretching out, vintage cassette player playing, bright lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "alpaca_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Barn Owl perched under cherry blossoms, headphones on, vintage cassette, pastel sunlight, serene lofi vibe, anime watercolor painting style",
            "A Barn Owl on a wooden fence, glowing sunrise, tea cup nearby, vibrant fields, peaceful lofi ambiance, anime watercolor painting style",
            "A Barn Owl resting near a sparkling stream, headphones on, blooming flowers, bright tranquil lofi scene, anime watercolor painting style",
            "A Barn Owl perched in a cozy library corner, surrounded by books, fairy lights glowing, lofi beats playing, anime watercolor painting style",
            "A Barn Owl on a rooftop terrace, cityscape at sunrise, vintage player nearby, serene and calm lofi mood, anime watercolor painting style",
            "A Barn Owl perched on a tree branch, sketchbook in talons, pastel sky, cheerful lofi atmosphere, anime watercolor painting style",
            "A Barn Owl by a glowing campfire, headphones on, colorful night sky above, relaxed lofi vibe, anime watercolor painting style",
            "A Barn Owl near a tranquil lake, tea cup beside, blooming wildflowers, serene pastel hues, peaceful lofi setting, anime watercolor painting style",
            "A Barn Owl resting on a hammock under a tree, vintage vinyl spinning, warm sunlight filtering, relaxed lofi mood, anime watercolor painting style",
            "A Barn Owl sitting on a wooden dock, headphones on, soft sunset glow on water, calm and serene lofi vibe, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "barn_owl_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "An Arctic Fox under auroras, headphones on, vintage cassette nearby, icy pastel glow, serene lofi vibe, anime watercolor painting style",
            "An Arctic Fox lounging on a snowy hill, tea cup beside, glowing sunrise, calm lofi mood, anime watercolor painting style",
            "An Arctic Fox sitting by a frozen lake, headphones on, blooming frost flowers, peaceful lofi ambiance, anime watercolor painting style",
            "An Arctic Fox in a cozy igloo, surrounded by fairy lights and books, warm pastel tones, lofi music playing, anime watercolor painting style",
            "An Arctic Fox perched on a snowy branch, sketchbook in paw, vibrant auroras above, cheerful lofi vibe, anime watercolor painting style",
            "An Arctic Fox near a glowing bonfire, vintage player playing, starry night sky, relaxed lofi mood, anime watercolor painting style",
            "An Arctic Fox resting on an ice floe, tea cup nearby, glowing pastel hues reflecting on water, serene lofi moment, anime watercolor painting style",
            "An Arctic Fox on a mountaintop, headphones on, colorful sunset sky, tranquil lofi scene, anime watercolor painting style",
            "An Arctic Fox curled up near a cozy fireplace, surrounded by books and a record player, warm inviting lofi atmosphere, anime watercolor painting style",
            "An Arctic Fox exploring an icy meadow, headphones on, frost-covered flowers shining, peaceful lofi setting, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "arctic_fox_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Pomeranian under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight, serene lofi vibe, anime watercolor painting style",
            "A Pomeranian lounging on a park bench, tea cup beside, glowing sunset, vibrant greenery, calm lofi mood, anime watercolor painting style",
            "A Pomeranian sitting by a cozy window, surrounded by books, fairy lights glowing, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Pomeranian resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Pomeranian in a hammock under a tree, vinyl spinning, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Pomeranian on a rooftop terrace, tea cup nearby, cityscape at sunrise, serene lofi ambiance, anime watercolor painting style",
            "A Pomeranian perched on a wooden dock, headphones on, soft sunset glow on water, peaceful lofi vibe, anime watercolor painting style",
            "A Pomeranian near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi setting, anime watercolor painting style",
            "A Pomeranian exploring a vibrant meadow, headphones on, wildflowers blooming, cheerful lofi moment, anime watercolor painting style",
            "A Pomeranian curled up near a cozy fireplace, surrounded by books and tea, warm lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "pomeranian_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Persian Cat under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight, serene lofi vibe, anime watercolor painting style",
            "A Persian Cat lounging on a park bench, tea cup beside, glowing sunset, vibrant greenery, calm lofi mood, anime watercolor painting style",
            "A Persian Cat sitting by a cozy window, surrounded by books, fairy lights glowing, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Persian Cat resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Persian Cat in a hammock under a tree, vinyl spinning, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Persian Cat on a rooftop terrace, tea cup nearby, cityscape at sunrise, serene lofi ambiance, anime watercolor painting style",
            "A Persian Cat perched on a wooden dock, headphones on, soft sunset glow on water, peaceful lofi vibe, anime watercolor painting style",
            "A Persian Cat near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi setting, anime watercolor painting style",
            "A Persian Cat exploring a vibrant meadow, headphones on, wildflowers blooming, cheerful lofi moment, anime watercolor painting style",
            "A Persian Cat curled up near a cozy fireplace, surrounded by books and tea, warm lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "persian_cat_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Husky under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Husky lounging by a snowy stream, tea cup beside, glowing sunlight, peaceful lofi mood, anime watercolor painting style",
            "A Husky resting on a mountaintop, headphones on, colorful sunrise sky, calm lofi ambiance, anime watercolor painting style",
            "A Husky sitting by a cozy cabin window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Husky in a hammock under pine trees, vintage player spinning, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Husky perched on a wooden dock by a lake, headphones on, soft sunset glow, tranquil lofi setting, anime watercolor painting style",
            "A Husky near a glowing campfire, vibrant auroras above, tea cup nearby, relaxed lofi vibe, anime watercolor painting style",
            "A Husky exploring a forest path, headphones on, surrounded by wildflowers, cheerful lofi scene, anime watercolor painting style",
            "A Husky curled up on a cozy rug near a fireplace, vintage player nearby, warm lofi mood, anime watercolor painting style",
            "A Husky sitting on a rooftop terrace, tea cup beside, sunrise cityscape, serene lofi moment, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "husky_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Ragdoll Cat under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Ragdoll Cat lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi atmosphere, anime watercolor painting style",
            "A Ragdoll Cat sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Ragdoll Cat resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Ragdoll Cat in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi mood, anime watercolor painting style",
            "A Ragdoll Cat perched on a wooden dock, pastel lake reflections, headphones on, tranquil lofi setting, anime watercolor painting style",
            "A Ragdoll Cat near a glowing campfire, colorful night sky above, vintage player playing, relaxed lofi vibe, anime watercolor painting style",
            "A Ragdoll Cat exploring a vibrant meadow, headphones on, wildflowers blooming, cheerful lofi moment, anime watercolor painting style",
            "A Ragdoll Cat curled up near a cozy fireplace, surrounded by books and tea, warm lofi mood, anime watercolor painting style",
            "A Ragdoll Cat on a rooftop garden, tea cup nearby, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "ragdoll_cat_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Macaw Parrot under cherry blossoms, headphones on, vibrant feathers glowing, pastel sunlight, serene lofi vibe, anime watercolor painting style",
            "A Macaw Parrot perched on a wooden dock, tea cup nearby, glowing sunset, colorful lake reflections, peaceful lofi mood, anime watercolor painting style",
            "A Macaw Parrot resting in a tropical forest, headphones on, blooming flowers, warm sunlight, cheerful lofi atmosphere, anime watercolor painting style",
            "A Macaw Parrot near a sparkling waterfall, vintage player playing, lush greenery around, calm lofi ambiance, anime watercolor painting style",
            "A Macaw Parrot perched on a rooftop terrace, sunrise cityscape, tea cup nearby, serene lofi vibe, anime watercolor painting style",
            "A Macaw Parrot flying over a vibrant meadow, headphones on, wildflowers below, bright cheerful lofi moment, anime watercolor painting style",
            "A Macaw Parrot near a glowing campfire, colorful feathers shimmering under the starry night, relaxed lofi mood, anime watercolor painting style",
            "A Macaw Parrot perched on a hammock between palm trees, vinyl spinning, golden sunlight filtering, relaxed tropical lofi scene, anime watercolor painting style",
            "A Macaw Parrot sitting by a cozy library window, surrounded by books and fairy lights, lofi music playing, anime watercolor painting style",
            "A Macaw Parrot exploring a vibrant garden, headphones on, colorful blooms all around, peaceful lofi setting, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "macaw_parrot_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Poodle under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Poodle lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Poodle sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Poodle resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Poodle in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Poodle perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Poodle near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Poodle exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Poodle curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Poodle on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "poodle_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Sphynx Cat under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Sphynx Cat lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Sphynx Cat sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Sphynx Cat resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Sphynx Cat in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Sphynx Cat perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Sphynx Cat near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Sphynx Cat exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Sphynx Cat curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Sphynx Cat on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "sphynx_cat_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Gentoo Penguin under auroras, headphones on, vintage cassette nearby, icy pastel glow, serene lofi vibe, anime watercolor painting style",
            "A Gentoo Penguin lounging on an ice floe, tea cup beside, glowing sunset, calm Antarctic lofi mood, anime watercolor painting style",
            "A Gentoo Penguin resting by a frozen stream, headphones on, frost flowers blooming, tranquil lofi scene, anime watercolor painting style",
            "A Gentoo Penguin in a cozy igloo, surrounded by fairy lights and books, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Gentoo Penguin perched on a snowy cliff, vintage player playing, auroras above, serene lofi ambiance, anime watercolor painting style",
            "A Gentoo Penguin near a glowing campfire, colorful night sky above, tea cup beside, relaxed lofi vibe, anime watercolor painting style",
            "A Gentoo Penguin sitting by a frozen lake, pastel reflections on the water, headphones on, peaceful lofi setting, anime watercolor painting style",
            "A Gentoo Penguin exploring a snowy meadow, frost-covered wildflowers shining, bright cheerful lofi scene, anime watercolor painting style",
            "A Gentoo Penguin curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Gentoo Penguin on a mountaintop, glowing sunrise behind, headphones on, serene lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "gentoo_penguin_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Dalmatian under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Dalmatian lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Dalmatian sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Dalmatian resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Dalmatian in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Dalmatian perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Dalmatian near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Dalmatian exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Dalmatian curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Dalmatian on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "dalmatian_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Bengal Cat under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Bengal Cat lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Bengal Cat sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Bengal Cat resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Bengal Cat in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Bengal Cat perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Bengal Cat near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Bengal Cat exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Bengal Cat curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Bengal Cat on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "bengal_cat_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Chihuahua under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Chihuahua lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Chihuahua sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Chihuahua resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Chihuahua in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Chihuahua perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Chihuahua near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Chihuahua exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Chihuahua curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Chihuahua on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "chihuahua_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Maine Coon Cat under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Maine Coon Cat lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Maine Coon Cat sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Maine Coon Cat resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Maine Coon Cat in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Maine Coon Cat perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Maine Coon Cat near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Maine Coon Cat exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Maine Coon Cat curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Maine Coon Cat on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "maine_coon_cat_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Bald Eagle under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Bald Eagle perched on a wooden dock, tea cup beside, golden sunset, vibrant lake reflections, peaceful lofi mood, anime watercolor painting style",
            "A Bald Eagle resting on a mountaintop, headphones on, glowing sunrise sky, tranquil lofi atmosphere, anime watercolor painting style",
            "A Bald Eagle near a sparkling stream, vintage player playing, blooming wildflowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Bald Eagle perched on a tree branch, pastel sky backdrop, serene lofi ambiance, vintage cassette nearby, anime watercolor painting style",
            "A Bald Eagle in a cozy cabin window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Bald Eagle near a glowing campfire, colorful night sky above, headphones on, relaxed lofi vibe, anime watercolor painting style",
            "A Bald Eagle flying over a vibrant meadow, headphones on, wildflowers blooming, cheerful lofi moment, anime watercolor painting style",
            "A Bald Eagle on a rooftop terrace, tea cup nearby, sunrise cityscape, peaceful lofi mood, anime watercolor painting style",
            "A Bald Eagle perched by a tranquil lake, pastel reflections, headphones on, serene lofi setting, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "bald_eagle_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Samoyed under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Samoyed lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Samoyed sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Samoyed resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Samoyed in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Samoyed perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Samoyed near a glowing campfire, vintage player playing, colorful night sky, relaxed lofi vibe, anime watercolor painting style",
            "A Samoyed exploring a vibrant meadow, headphones on, wildflowers blooming, bright cheerful lofi moment, anime watercolor painting style",
            "A Samoyed curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Samoyed on a rooftop garden, tea cup beside, glowing sunrise cityscape, serene lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "samoyede_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Cockatiel under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Cockatiel perched on a wooden dock, tea cup beside, golden sunset, vibrant lake reflections, peaceful lofi mood, anime watercolor painting style",
            "A Cockatiel resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Cockatiel perched on a rooftop garden, sunrise cityscape, tea cup nearby, tranquil lofi ambiance, anime watercolor painting style",
            "A Cockatiel in a cozy room, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Cockatiel near a glowing campfire, vibrant night sky, headphones on, vintage player nearby, relaxed lofi vibe, anime watercolor painting style",
            "A Cockatiel flying over a vibrant meadow, colorful wildflowers below, headphones on, cheerful lofi moment, anime watercolor painting style",
            "A Cockatiel perched on a tree branch, pastel sky backdrop, serene lofi setting, vintage cassette nearby, anime watercolor painting style",
            "A Cockatiel exploring a lush garden, headphones on, surrounded by blooming flowers, peaceful lofi vibe, anime watercolor painting style",
            "A Cockatiel by a calm lake, pastel reflections, headphones on, tea cup nearby, tranquil lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "cockatiel_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Sea Otter floating among pastel waves, headphones on, vintage cassette nearby, serene lofi vibe, anime watercolor painting style",
            "A Sea Otter lounging on a wooden dock, tea cup beside, glowing sunset reflections, peaceful lofi mood, anime watercolor painting style",
            "A Sea Otter resting by a sparkling tide pool, headphones on, blooming coastal flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Sea Otter holding a vintage player, floating in calm waters, pastel sky above, tranquil lofi atmosphere, anime watercolor painting style",
            "A Sea Otter near a glowing campfire on a beach, colorful night sky, headphones on, relaxed lofi vibe, anime watercolor painting style",
            "A Sea Otter perched on a rock, surrounded by ocean waves, headphones on, serene and peaceful lofi setting, anime watercolor painting style",
            "A Sea Otter floating with a tea cup, pastel lake reflections, headphones on, tranquil lofi moment, anime watercolor painting style",
            "A Sea Otter exploring a coastal meadow, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Sea Otter near a cozy seaside cabin, vintage player nearby, glowing pastel tones, warm lofi mood, anime watercolor painting style",
            "A Sea Otter resting under sunset skies, floating among soft waves, headphones on, serene lofi scene, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "sea_otter_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A White Peacock under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A White Peacock perched on a wooden dock, tea cup beside, glowing sunset reflections, tranquil lofi mood, anime watercolor painting style",
            "A White Peacock resting in a vibrant meadow, headphones on, surrounded by wildflowers, bright cheerful lofi ambiance, anime watercolor painting style",
            "A White Peacock near a sparkling stream, vintage player playing, pastel sky reflections, peaceful lofi scene, anime watercolor painting style",
            "A White Peacock in a cozy garden, surrounded by books and fairy lights, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A White Peacock near a glowing campfire, colorful feathers shimmering, headphones on, serene lofi atmosphere, anime watercolor painting style",
            "A White Peacock perched on a rooftop garden, tea cup beside, sunrise cityscape, peaceful lofi vibe, anime watercolor painting style",
            "A White Peacock exploring a lush forest, headphones on, sunlight streaming through trees, bright lofi moment, anime watercolor painting style",
            "A White Peacock resting by a tranquil lake, pastel reflections, headphones on, vintage cassette nearby, serene lofi setting, anime watercolor painting style",
            "A White Peacock floating gracefully in a pond, surrounded by blooming lotus flowers, calm lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "white_peacock_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Sulcata Tortoise under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Sulcata Tortoise lounging on a grassy hill, tea cup beside, glowing sunset, vibrant wildflowers, peaceful lofi mood, anime watercolor painting style",
            "A Sulcata Tortoise resting near a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Sulcata Tortoise near a cozy desert hut, surrounded by fairy lights and books, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A Sulcata Tortoise basking by a campfire, glowing night sky above, vintage player nearby, relaxed lofi atmosphere, anime watercolor painting style",
            "A Sulcata Tortoise exploring a vibrant meadow, headphones on, surrounded by blooming flowers, cheerful lofi ambiance, anime watercolor painting style",
            "A Sulcata Tortoise perched by a calm pond, pastel reflections, headphones on, tranquil lofi setting, anime watercolor painting style",
            "A Sulcata Tortoise in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi vibe, anime watercolor painting style",
            "A Sulcata Tortoise on a rooftop garden, tea cup beside, sunrise cityscape, peaceful lofi mood, anime watercolor painting style",
            "A Sulcata Tortoise walking through a lush forest, headphones on, sunlight streaming through leaves, serene lofi scene, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "sulcata_tortoise_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Seal floating in pastel waves, headphones on, vintage cassette nearby, serene lofi vibe, anime watercolor painting style",
            "A Seal lounging on a sunny rock, tea cup beside, glowing ocean sunset, peaceful lofi mood, anime watercolor painting style",
            "A Seal resting by a sparkling tide pool, headphones on, blooming coastal flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Seal near a cozy beach hut, surrounded by fairy lights and books, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A Seal basking near a campfire, colorful night sky above, vintage player nearby, relaxed lofi atmosphere, anime watercolor painting style",
            "A Seal swimming through vibrant coral reefs, headphones on, bright tropical vibe, tranquil lofi moment, anime watercolor painting style",
            "A Seal perched on an ice floe, tea cup nearby, pastel reflections, serene lofi setting, anime watercolor painting style",
            "A Seal near a calm lagoon, surrounded by wildflowers, headphones on, peaceful lofi ambiance, anime watercolor painting style",
            "A Seal in a hammock between driftwood trees, vinyl spinning, golden sunlight filtering, relaxed lofi mood, anime watercolor painting style",
            "A Seal exploring a coastal meadow, headphones on, blooming wildflowers, cheerful lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "seal_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Ferret under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Ferret lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Ferret resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Ferret exploring a vibrant meadow, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Ferret curled up near a cozy fireplace, surrounded by books and tea, warm lofi atmosphere, anime watercolor painting style",
            "A Ferret perched on a wooden dock, pastel lake reflections, vintage player nearby, tranquil lofi setting, anime watercolor painting style",
            "A Ferret near a glowing campfire, colorful night sky above, headphones on, serene lofi vibe, anime watercolor painting style",
            "A Ferret in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi mood, anime watercolor painting style",
            "A Ferret near a cozy window, surrounded by fairy lights and books, pastel tones, lofi music playing, anime watercolor painting style",
            "A Ferret sitting on a rooftop terrace, tea cup beside, sunrise cityscape, peaceful lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "ferret_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Burrowing Owl under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Burrowing Owl perched on a wooden fence, tea cup beside, glowing sunset, vibrant meadow, peaceful lofi mood, anime watercolor painting style",
            "A Burrowing Owl resting near a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Burrowing Owl exploring a desert landscape, surrounded by wildflowers, headphones on, tranquil lofi atmosphere, anime watercolor painting style",
            "A Burrowing Owl near a glowing campfire, colorful night sky above, vintage player nearby, relaxed lofi vibe, anime watercolor painting style",
            "A Burrowing Owl perched by a calm pond, pastel reflections, headphones on, serene lofi setting, anime watercolor painting style",
            "A Burrowing Owl in a cozy burrow window, surrounded by books and fairy lights, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A Burrowing Owl sitting on a rooftop garden, tea cup beside, sunrise cityscape, peaceful lofi ambiance, anime watercolor painting style",
            "A Burrowing Owl resting by a forest clearing, sunlight streaming through trees, headphones on, cheerful lofi mood, anime watercolor painting style",
            "A Burrowing Owl perched near a blooming cactus, vintage cassette nearby, desert sunset, relaxed lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "burrowing_owl_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "An Akita Inu under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "An Akita Inu lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "An Akita Inu resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "An Akita Inu exploring a vibrant meadow, surrounded by wildflowers, headphones on, tranquil lofi atmosphere, anime watercolor painting style",
            "An Akita Inu near a glowing campfire, colorful night sky above, vintage player nearby, relaxed lofi vibe, anime watercolor painting style",
            "An Akita Inu perched on a wooden dock, pastel lake reflections, tea cup nearby, serene lofi setting, anime watercolor painting style",
            "An Akita Inu curled up near a cozy fireplace, surrounded by books and tea, warm lofi ambiance, anime watercolor painting style",
            "An Akita Inu in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi mood, anime watercolor painting style",
            "An Akita Inu near a cozy window, surrounded by fairy lights and books, pastel tones, lofi music playing, anime watercolor painting style",
            "An Akita Inu sitting on a rooftop garden, tea cup beside, glowing sunrise cityscape, peaceful lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "akita_inu_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Highland Cow under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Highland Cow lounging on a grassy hill, tea cup beside, golden sunset, vibrant meadow, peaceful lofi mood, anime watercolor painting style",
            "A Highland Cow resting near a sparkling stream, headphones on, blooming wildflowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Highland Cow in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Highland Cow perched by a calm pond, pastel reflections, tea cup nearby, serene lofi setting, anime watercolor painting style",
            "A Highland Cow near a glowing campfire, colorful night sky above, vintage player nearby, relaxed lofi vibe, anime watercolor painting style",
            "A Highland Cow exploring a vibrant meadow, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Highland Cow near a cozy barn window, surrounded by books and fairy lights, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A Highland Cow sitting on a wooden dock, glowing lake reflections, tea cup beside, tranquil lofi moment, anime watercolor painting style",
            "A Highland Cow under a blooming tree, sunlight streaming through branches, headphones on, serene lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "highland_cow_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Kiwi under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Kiwi perched on a wooden dock, tea cup beside, golden sunset, vibrant reflections, peaceful lofi mood, anime watercolor painting style",
            "A Kiwi exploring a lush meadow, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Kiwi resting near a sparkling stream, vintage player playing, blooming flowers, tranquil lofi scene, anime watercolor painting style",
            "A Kiwi near a cozy burrow entrance, surrounded by fairy lights and books, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A Kiwi perched near a glowing campfire, colorful night sky above, serene lofi atmosphere, anime watercolor painting style",
            "A Kiwi sitting by a calm pond, pastel reflections, headphones on, peaceful lofi moment, anime watercolor painting style",
            "A Kiwi wandering through a vibrant forest, sunlight streaming through leaves, headphones on, relaxed lofi vibe, anime watercolor painting style",
            "A Kiwi near a blooming tree, soft sunlight filtering, vintage cassette nearby, serene lofi mood, anime watercolor painting style",
            "A Kiwi curled up in a hammock under a tree, vinyl spinning, golden light filtering, relaxed lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "kiwi_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A White Bengal Tiger under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A White Bengal Tiger lounging by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A White Bengal Tiger resting on a grassy hill, tea cup beside, golden sunset, tranquil lofi ambiance, anime watercolor painting style",
            "A White Bengal Tiger near a calm lake, pastel reflections, vintage player nearby, peaceful lofi mood, anime watercolor painting style",
            "A White Bengal Tiger curled up in a hammock under a tree, vinyl spinning, golden sunlight filtering, relaxed lofi vibe, anime watercolor painting style",
            "A White Bengal Tiger exploring a vibrant meadow, surrounded by wildflowers, headphones on, cheerful lofi atmosphere, anime watercolor painting style",
            "A White Bengal Tiger near a glowing campfire, colorful night sky above, serene lofi moment, anime watercolor painting style",
            "A White Bengal Tiger perched by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A White Bengal Tiger sitting on a wooden dock, glowing lake reflections, tea cup nearby, tranquil lofi scene, anime watercolor painting style",
            "A White Bengal Tiger under a blooming tree, sunlight streaming through branches, headphones on, serene lofi vibe, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "white_bengal_tiger_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Betta Fish swimming under cherry blossoms, pastel water reflections, headphones on, serene lofi vibe, anime watercolor painting style",
            "A Betta Fish in a calm aquarium, surrounded by glowing fairy lights, vintage cassette nearby, peaceful lofi mood, anime watercolor painting style",
            "A Betta Fish near colorful coral, headphones on, sunlight filtering through water, tranquil lofi atmosphere, anime watercolor painting style",
            "A Betta Fish resting in a pond with blooming lotus flowers, soft pastel hues, serene lofi scene, anime watercolor painting style",
            "A Betta Fish floating near an underwater treasure chest, vintage player nearby, glowing coral light, relaxed lofi vibe, anime watercolor painting style",
            "A Betta Fish exploring a vibrant underwater garden, surrounded by soft seaweed and flowers, cheerful lofi ambiance, anime watercolor painting style",
            "A Betta Fish near a glowing underwater campfire, colorful night ocean above, serene lofi mood, anime watercolor painting style",
            "A Betta Fish swimming through a pastel reef, headphones on, vibrant reflections, peaceful lofi setting, anime watercolor painting style",
            "A Betta Fish in a small pond, surrounded by glowing stones, vintage vinyl spinning nearby, relaxed lofi scene, anime watercolor painting style",
            "A Betta Fish in a cozy aquarium corner, books stacked outside, fairy lights glowing, serene lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "betta_fish_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Coconut Crab under a palm tree, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Coconut Crab lounging on a sandy beach, tea cup beside, glowing sunset, calm ocean waves, peaceful lofi mood, anime watercolor painting style",
            "A Coconut Crab exploring a tide pool, surrounded by colorful shells, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Coconut Crab resting near a sparkling lagoon, vintage player playing, pastel reflections, tranquil lofi scene, anime watercolor painting style",
            "A Coconut Crab near a cozy beach hut, fairy lights glowing, lofi music playing, warm pastel tones, anime watercolor painting style",
            "A Coconut Crab climbing a driftwood tree, soft sunlight filtering through leaves, serene lofi atmosphere, anime watercolor painting style",
            "A Coconut Crab by a glowing campfire on the beach, colorful night sky above, relaxed lofi vibe, anime watercolor painting style",
            "A Coconut Crab perched on a rock, surrounded by blooming coastal flowers, headphones on, tranquil lofi mood, anime watercolor painting style",
            "A Coconut Crab sitting near a calm tide pool, vintage vinyl spinning nearby, serene pastel tones, lofi moment, anime watercolor painting style",
            "A Coconut Crab wandering along a tropical shoreline, headphones on, sunlight reflecting on water, relaxed lofi vibe, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "coconut_crab_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Turkish Angora Cat under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Turkish Angora Cat lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Turkish Angora Cat sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Turkish Angora Cat resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Turkish Angora Cat in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Turkish Angora Cat perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Turkish Angora Cat near a glowing campfire, colorful night sky above, vintage player nearby, serene lofi vibe, anime watercolor painting style",
            "A Turkish Angora Cat exploring a vibrant meadow, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Turkish Angora Cat curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Turkish Angora Cat sitting on a rooftop garden, tea cup beside, glowing sunrise cityscape, peaceful lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "turkish_angora_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Border Collie under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Border Collie lounging on a park bench, tea cup beside, golden sunset, vibrant greenery, peaceful lofi mood, anime watercolor painting style",
            "A Border Collie sitting by a cozy window, surrounded by books and fairy lights, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Border Collie resting by a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Border Collie in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Border Collie perched on a wooden dock, pastel lake reflections, tea cup nearby, tranquil lofi setting, anime watercolor painting style",
            "A Border Collie near a glowing campfire, colorful night sky above, vintage player nearby, serene lofi vibe, anime watercolor painting style",
            "A Border Collie exploring a vibrant meadow, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Border Collie curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Border Collie sitting on a rooftop garden, tea cup beside, glowing sunrise cityscape, peaceful lofi ambiance, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "border_collie_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Common Starling under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Common Starling perched on a wooden dock, tea cup beside, glowing sunset, vibrant lake reflections, peaceful lofi mood, anime watercolor painting style",
            "A Common Starling resting near a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Common Starling exploring a vibrant meadow, surrounded by wildflowers, headphones on, tranquil lofi atmosphere, anime watercolor painting style",
            "A Common Starling near a glowing campfire, colorful night sky above, vintage player nearby, serene lofi ambiance, anime watercolor painting style",
            "A Common Starling perched on a rooftop garden, tea cup beside, glowing sunrise cityscape, peaceful lofi mood, anime watercolor painting style",
            "A Common Starling perched on a tree branch, pastel sky backdrop, headphones on, cheerful lofi moment, anime watercolor painting style",
            "A Common Starling near a calm pond, pastel reflections, vintage cassette nearby, serene lofi setting, anime watercolor painting style",
            "A Common Starling in a lush garden, headphones on, surrounded by blooming flowers, bright lofi vibe, anime watercolor painting style",
            "A Common Starling under a blooming tree, sunlight streaming through branches, headphones on, tranquil lofi scene, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "common_starling_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Miniature Pig under cherry blossoms, headphones on, vintage cassette nearby, pastel sunlight glow, serene lofi vibe, anime watercolor painting style",
            "A Miniature Pig lounging on a grassy hill, tea cup beside, golden sunset, vibrant meadow, peaceful lofi mood, anime watercolor painting style",
            "A Miniature Pig resting near a sparkling stream, headphones on, blooming flowers, bright cheerful lofi scene, anime watercolor painting style",
            "A Miniature Pig in a hammock under a tree, vinyl spinning nearby, golden sunlight filtering, relaxed lofi atmosphere, anime watercolor painting style",
            "A Miniature Pig perched near a calm pond, pastel reflections, tea cup beside, tranquil lofi setting, anime watercolor painting style",
            "A Miniature Pig exploring a vibrant garden, surrounded by wildflowers, headphones on, cheerful lofi ambiance, anime watercolor painting style",
            "A Miniature Pig near a glowing campfire, colorful night sky above, vintage player nearby, serene lofi vibe, anime watercolor painting style",
            "A Miniature Pig sitting on a rooftop terrace, tea cup beside, glowing sunrise cityscape, peaceful lofi moment, anime watercolor painting style",
            "A Miniature Pig curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi mood, anime watercolor painting style",
            "A Miniature Pig under a blooming tree, sunlight streaming through branches, headphones on, tranquil lofi mood, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "miniature_pig_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Bottlenose Dolphin swimming under pastel waves, headphones on, vintage cassette nearby, serene lofi vibe, anime watercolor painting style",
            "A Bottlenose Dolphin near a coral reef, glowing sunlight filtering through water, headphones on, tranquil lofi atmosphere, anime watercolor painting style",
            "A Bottlenose Dolphin floating near a sparkling lagoon, vintage player nearby, pastel reflections, peaceful lofi scene, anime watercolor painting style",
            "A Bottlenose Dolphin leaping under a glowing sunset, vibrant ocean hues, headphones on, cheerful lofi mood, anime watercolor painting style",
            "A Bottlenose Dolphin near a beach bonfire, colorful night sky above, serene lofi vibe, anime watercolor painting style",
            "A Bottlenose Dolphin exploring a tropical reef, surrounded by colorful coral and fish, headphones on, bright lofi ambiance, anime watercolor painting style",
            "A Bottlenose Dolphin swimming near a calm tide pool, vintage vinyl spinning nearby, tranquil lofi setting, anime watercolor painting style",
            "A Bottlenose Dolphin in a cozy underwater cave, glowing fairy lights, serene lofi atmosphere, anime watercolor painting style",
            "A Bottlenose Dolphin floating under the moonlight, headphones on, peaceful ocean reflections, relaxed lofi mood, anime watercolor painting style",
            "A Bottlenose Dolphin swimming through a pastel reef, sunlight streaming through waves, cheerful lofi scene, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "bottlenose_dolphin_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A Polar Bear Cub under auroras, headphones on, vintage cassette nearby, icy pastel glow, serene lofi vibe, anime watercolor painting style",
            "A Polar Bear Cub lounging on a snowy hill, tea cup beside, glowing sunset, peaceful Arctic lofi mood, anime watercolor painting style",
            "A Polar Bear Cub resting by a frozen stream, headphones on, frost flowers blooming, tranquil lofi scene, anime watercolor painting style",
            "A Polar Bear Cub near a cozy igloo, surrounded by fairy lights and books, warm pastel tones, lofi music playing, anime watercolor painting style",
            "A Polar Bear Cub perched on an ice floe, pastel reflections on water, tea cup nearby, serene lofi setting, anime watercolor painting style",
            "A Polar Bear Cub exploring a snowy meadow, headphones on, wildflowers poking through snow, cheerful lofi ambiance, anime watercolor painting style",
            "A Polar Bear Cub near a glowing campfire, colorful night sky above, vintage player nearby, relaxed lofi vibe, anime watercolor painting style",
            "A Polar Bear Cub sitting on a mountaintop, headphones on, glowing sunrise behind, tranquil lofi mood, anime watercolor painting style",
            "A Polar Bear Cub curled up near a cozy fireplace, surrounded by books and tea, warm inviting lofi scene, anime watercolor painting style",
            "A Polar Bear Cub wandering through an icy forest, pastel light streaming, headphones on, serene lofi atmosphere, anime watercolor painting style",
        ],
        "title": "",
        "file_name": "polar_bear_cub_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
]


INIT_NORMAL_REQUEST = [
    {
        "short_description": [
            "Santa Claus checking his gift list in a cozy toy workshop filled with toys and tools, realistic lighting and details"
        ],
        "title": "Christmas Music",
        "file_name": "christmas_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
    {
        "short_description": [
            "A peaceful scene of a woman in a white summer dress sitting on a wooden swing in a green field of yellow flowers under warm sunlight, realistic lighting and details"
        ],
        "title": "Morning Music",
        "file_name": "morning_music",
        "day_of_week": [0,1,2,3,4,5,6],
    },
]

DATASET_TRAINED_FOLDER = Path(os.getenv('DATASET_TRAINED_FOLDER', "/dataset_trained"))

