THUMBNAIL_STYLE_LIST = [
    "realistic photo",
    "illustration",
    "cartoon fun",
    "comic",
    "dark",
    "water color",
    "pixel art",
    "surreal",
    "oil painting",
    "nature",
    "ink print",
    "pencil",
    "retrowave",
    "vintage japanese",
    "lifestyle",
    "collage",
    "glitchart",
    "retroglow",
    "lowkey cinematic",
    "analog memories",
    "trippy illustration",
    "fantasy cartoon",
    "pastel paint",
    "arcadebits",
    "squishy 3d",
    "product photography",
    "historical",
    "felted",
    "podium",
    "redveil",
    "darklight dreamscaped",
    "dreamlandscapes",
    "linework",
    "sonny anime",
    "soft pasty",
    "soft retro",
    "plushy world",
    "film effect",
    "anime",
    "warnand cold",
    "sparking",
    "blurry long exposure",
    "flutted glass",
    "glimmerish",
    "forties influence",
    "dadapop",
    "eighties movie",
    "renaissance fashion",
    "fineart",
    "neo classicart",
    "highend light",
    "fantasy anime",
    "3d colorful"
]
